# Generated by Django 3.1.3 on 2023-05-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codeudor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.SmallIntegerField(max_length=10)),
                ('nombreCodeudor', models.CharField(help_text='Ingrese el Nombre del Codeudor', max_length=60)),
                ('apellidoCodeudor', models.CharField(help_text='Ingrese el Apellido del Codeudor', max_length=60)),
                ('ciudadCodeudor', models.CharField(help_text='Ingrese la ciudad donde reside', max_length=100)),
                ('telefonoCodeudor', models.CharField(help_text='Ingrese el Telefono del Codeudor', max_length=12)),
                ('direccionCodeudor', models.CharField(help_text='Ingrese la Direccion del Codeudor', max_length=100)),
                ('correoCodeudor', models.EmailField(help_text='Ingrese el Correo del Codeudor', max_length=100)),
                ('PosibleSocio', models.BooleanField(help_text='Ingrese el Correo del Codeudor')),
            ],
            options={
                'verbose_name': 'Codeudor',
                'verbose_name_plural': 'Codeudor',
            },
        ),
    ]
