# Generated by Django 3.1.3 on 2023-05-17 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        ('codeudor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pTiempoEstipulado', models.SmallIntegerField(verbose_name='Periosde de tiempo estipulado')),
                ('tasaInteres', models.PositiveIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('valorPrestamo', models.FloatField(verbose_name='Valor prestamo')),
                ('cuotaMensual', models.PositiveSmallIntegerField(verbose_name='Cuotas mensuales')),
                ('plazoMeses', models.PositiveSmallIntegerField(verbose_name='Plazo mensuales')),
                ('codeudor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeudor.codeudor', verbose_name='Codeudor')),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prestamos.modalidad', verbose_name='Modalidad de pago')),
                ('socios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
            options={
                'verbose_name': 'venta producto',
                'verbose_name_plural': 'Ventas Productos',
            },
        ),
    ]
