# Generated by Django 3.1.3 on 2023-05-17 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=50, verbose_name='Nombre de la empresa')),
            ],
            options={
                'verbose_name': 'Nombre empresa',
                'verbose_name_plural': 'Nombres de empresas',
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSocio', models.CharField(max_length=60, verbose_name='Nombre del socio')),
                ('cedula', models.PositiveIntegerField(max_length=10)),
                ('apellidoSocio', models.CharField(help_text='Ingrese el Apellido del Socio', max_length=60)),
                ('ciudadSocio', models.CharField(help_text='Ingrese la ciudad donde reside', max_length=100)),
                ('telefonoSocio', models.CharField(help_text='Ingrese el Telefono del Socio', max_length=12)),
                ('direccionSocio', models.CharField(help_text='Ingrese la Direccion del Socio', max_length=100)),
                ('correoSocio', models.EmailField(help_text='Ingrese el Correo del Socio', max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.empresa')),
            ],
            options={
                'verbose_name': 'socio',
                'verbose_name_plural': ' socios',
            },
        ),
    ]
